### PR TITLE
Coded Fetching of all APIs then produce Products array and save it locally

### LINKED ISSUE #25: Code to Import All API data.
Relates #8 

Objective: Import All API data in the local storage, so user can move between pages locally not wait every time API loads

- [ ] Fetch API 1 & Store it local
- [ ] Fetch API 2 & Store it local
- [ ] Fetch API 3 & Store it local
- [ ] Create Array of All Data and store it local.

  - API (1): [Makeup Products](https://makeup-api.herokuapp.com/)
  - API (2): [Jewellery](https://fakestoreapi.com/products/category/jewelery)
  - API (3): [Exchange Rates](https://www.exchangerate-api.com/)

### PR DESCRIPTION
**Pull request by MMansour87**
Coded Fetching of all APIs then manipulated API 1 and 2 to create all products array and save it in local storage#25

### CODE REVIEW

**Review by abdulrahman-2020 — DISMISSED** [review]
👍👌Great!

**Review by mo7amedehab97 — DISMISSED** [review]
will done

**Review by EmanHass — DISMISSED** [review]

**Review by abdulrahman-2020 — APPROVED** [review]

**Review by EmanHass — APPROVED** [review]

**Review by lina-jamal — APPROVED** [review]
great job mutasem 
you use  ```  async-await ```  that's great  👍

**Comment by MMansour87** [comment]
> great job mutasem
> you use ` async-await` that's great 👍

Abdulrhman Idea

**Pull request merged**
