### PR TITLE
styling cart page

### LINKED ISSUE #66: create cart page with css
Styling the cart page relates #46

### PR DESCRIPTION
**Pull request by mo7amedehab97**
Relates #66 

styling cart page 

_Final Result_
127 0 0 1_5500_ShoppingCart_ShoppingCart html(iPhone X)

### CODE REVIEW

**Review by abdulrahman-2020 — DISMISSED** [review]

**Review by MMansour87 — CHANGES_REQUESTED** [review]
Well Done
But please, Text in Checkout button must be white

**Comment by mo7amedehab97** [comment]
> Well Done
> But please, Text in Checkout button must be white

**Comment by mo7amedehab97** [comment]
thanks, mutasem i just did the changes you requested

**Review by EmanHass — DISMISSED** [review]

**Review by MMansour87 — DISMISSED** [review]
Well done

**Comment by lina-jamal** [comment]
solve conflict

**Review by MMansour87 — APPROVED** [review]

**Review by lina-jamal — APPROVED** [review]

**Review by EmanHass — APPROVED** [review]

**Pull request merged**
